name: CI

on:
  pull_request:
    branches:
      - master
      - dev
      - dev-*

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows ]
    steps:
    - name: Notify slack success
      if: success()
      id: slack # IMPORTANT: reference this step ID value in future Slack steps
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1.1.1
      with:
        channel: github-actions
        status: STARTING
        color: warning
    
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet build SecureNative.Tests
    - run: dotnet test SecureNative.Tests
    
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1.1.1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: github-actions
        status: SUCCESS
        color: good

    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1.1.1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: github-actions
        status: FAILED
        color: danger
